In [1]:
scores = [78, 69, 65]
new_scores = []

for score in scores:
    new_scores.append(score + 3)

new_scores

[81, 72, 68]

In [2]:
scores = [78, 69, 65]
new_scores = [score + 3 for score in scores]
new_scores

[81, 72, 68]

In [3]:
scores = [78, 69, 65]
scores*2

[78, 69, 65, 78, 69, 65]

In [7]:
import numpy as np

scores = np.array([78, 69, 65])
print(type(scores))
scores + 3

<class 'numpy.ndarray'>


array([81, 72, 68])

In [9]:
print(scores.sum())
print(scores.mean())
print(scores.std())
print(scores.min())
print(scores.max())
print(np.median(scores))

212
70.66666666666667
5.436502143433363
65
78
69.0


In [10]:
students = np.array([
    [67, 94, 65],
    [78, 92, 68],
    [59, 92, 87]
    ])
students

array([[67, 94, 65],
       [78, 92, 68],
       [59, 92, 87]])

In [11]:
#常用的查詢屬性
students.ndim, students.size, students.shape, students.dtype

(2, 9, (3, 3), dtype('int64'))

In [12]:
students[0,0]

np.int64(67)

In [13]:
#第1位學生分數
students[0,:]

array([67, 94, 65])

In [14]:
#前2個學生
students[0:2,:]

array([[67, 94, 65],
       [78, 92, 68]])

In [18]:
#最後2個學生
students[-2:, :]
students[-2:,]

array([[78, 92, 68],
       [59, 92, 87]])

In [ ]:
#國文 第一欄分數
students[:,0]

array([67, 78, 59])

In [21]:
#前兩欄分數

students[:,:2]

array([[67, 94],
       [78, 92],
       [59, 92]])